### ISSUE TITLE
Firefox Addon

### ISSUE THREAD

**Issue by anthonymasure** [ineffyble/tooter#17]
What about the Firefox Addon development? Would be great to have Tooter on a true "free" browser!

**Comment by ineffyble** [comment]
TL;DR Firefox version has been awaiting official review for over a month.

Tooter up to 0.25 is Firefox compatible. The initial submission to the Firefox Addons review team in December 2016 was rejected due to security issues.

Those issues were fixed and a later version has been in the review queue for several weeks. I'm waiting on that version to be approved, and will then make the necessary changes to the current version to sort out incompatibilities.

**Comment by anthonymasure** [comment]
Great, thanks! Hope that it would be online as soon as possible

**Comment by Dreckiger-Dan** [comment]
It looks like the addon has been approved: https://addons.mozilla.org/en-US/firefox/addon/tooter/

**Comment by anthonymasure** [comment]
Thank you, it works well! You can close the issue.

**Comment by ineffyble** [comment]
Closing now - there was a brief technical issue when it was first published, but that appears to have been resolved.
